--TABLA CATEGORIA
CREATE TABLE TBL_CATEGORIA(
    nIdCategoria INT NOT NULL IDENTITY(1,1) PRIMARY KEY ,
    sNombre VARCHAR(MAX),
	sDescripcion VARCHAR(MAX),
	bEstado BIT
)
GO

--TABLA PRODUCTO
CREATE TABLE TBL_PRODUCTO(
    nIdProducto INT NOT NULL IDENTITY(1,1) PRIMARY KEY ,
    sNombre VARCHAR(MAX),	
	bEstado BIT
)
GO

--TABLA CATEGORIA X PRODUCTO
CREATE TABLE TBL_CAT_PROD(
    nIdCatProd INT NOT NULL IDENTITY(1,1) PRIMARY KEY ,
    nIdAlmacen INT,
	FOREIGN KEY (nIdAlmacen) REFERENCES TBL_ALMACEN(nIdAlmacen),   
	nIdCategoria INT,
	FOREIGN KEY (nIdCategoria) REFERENCES TBL_CATEGORIA(nIdCategoria),
	nIdProducto INT
	FOREIGN KEY (nIdProducto) REFERENCES TBL_PRODUCTO(nIdProducto),
)
GO

--TABLA LOTE
CREATE TABLE TBL_LOTE(
    nIdLote INT NOT NULL IDENTITY(1,1) PRIMARY KEY ,
    sNombreLote VARCHAR(MAX),
	dFechaFab DATE,
	dFechaVenc DATE
)
GO

--TABLA UNIDAD MEDIDA
CREATE TABLE TBL_UNIDADMEDIDA(
    nIdUnidadMedida INT NOT NULL IDENTITY(1,1) PRIMARY KEY ,
    sNombre VARCHAR(MAX),
)
GO

--TABLA DETALLE PRODUCTO
CREATE TABLE TBL_DET_PRODUCTO(
    nIdDetProd INT NOT NULL IDENTITY(1,1) PRIMARY KEY ,
    nIdProducto INT,
	FOREIGN KEY (nIdProducto) REFERENCES TBL_PRODUCTO(nIdProducto),
	sDescripcion VARCHAR(MAX),
	nIdUnidadMedida INT,
	FOREIGN KEY (nIdUnidadMedida) REFERENCES TBL_UNIDADMEDIDA(nIdUnidadMedida),
	nCantidad INT ,
	nPrecio INT ,
	nIdLote INT,
)
GO
