USE DB_SISGAPO
GO

--TABLA DOCUMENTOS
CREATE TABLE TBL_DOCUMENTO(
    nIdDocumento INT NOT NULL IDENTITY(1,1) PRIMARY KEY ,
    sNombreDoc VARCHAR(100),
)
GO

--TABLA ROLES
CREATE TABLE TBL_ROL(
    nIdRol INT NOT NULL IDENTITY(1,1) PRIMARY KEY ,
    sNombreRol VARCHAR(100)    
)
GO

--TABLA ZONAS
CREATE TABLE TBL_ZONA(
    nIdZona INT NOT NULL IDENTITY(1,1) PRIMARY KEY ,
    sNombre VARCHAR(MAX),
	sRutaImagen VARCHAR(MAX)
)
GO

--TABLA USUARIOS
CREATE TABLE TBL_USUARIO(
    nIdUsuario INT NOT NULL IDENTITY(1,1) PRIMARY KEY ,
    sNombres VARCHAR(MAX),
	sApellidos VARCHAR(MAX),
	nTipoDoc INT,
    FOREIGN KEY (nTipoDoc) REFERENCES TBL_DOCUMENTO(nIdDocumento),
    sNumDoc VARCHAR(15),
	sSexo VARCHAR(1),
	nRol INT,
    FOREIGN KEY (nRol) REFERENCES TBL_ROL(nIdRol),   
	sDireccion VARCHAR(MAX),
	nTelefono INT,
	dFechaNacimiento DATE,
	bEstado BIT NOT NULL DEFAULT 1
)
GO

--TABLA LOGIN
CREATE TABLE TBL_LOGIN(
    nIdUsuario INT NOT NULL,
	FOREIGN KEY (nIdUsuario) REFERENCES TBL_USUARIO(nIdUsuario),
    sNombreUsuario VARCHAR(100),
    sContrasenia VARCHAR(MAX)
)
GO

--TABLA ALMACEN
CREATE TABLE TBL_ALMACEN(
    nIdAlmacen INT NOT NULL IDENTITY(1,1) PRIMARY KEY ,
    sNombre VARCHAR(MAX),
	sDireccion VARCHAR(MAX),
	nIdSupervisor INT NOT NULL,
	FOREIGN KEY (nIdSupervisor) REFERENCES TBL_USUARIO(nIdUsuario),
	nIdZona INT NOT NULL,
	FOREIGN KEY (nIdZona) REFERENCES TBL_ZONA(nIdZona),
    bEstado BIT NOT NULL DEFAULT 1
)
GO

/*-------------------TABLAS 2-3 ITERACIÓN-------------------*/

--TABLA CATEGORIA
CREATE TABLE TBL_CATEGORIA(
    nIdCategoria INT NOT NULL IDENTITY(1,1) PRIMARY KEY ,
    sNombre VARCHAR(MAX),
	sDescripcion VARCHAR(MAX),
	bEstado BIT
)
GO

--TABLA PRODUCTO
CREATE TABLE TBL_PRODUCTO(
    nIdProducto INT NOT NULL IDENTITY(1,1) PRIMARY KEY ,
    sNombre VARCHAR(MAX),	
	bEstado BIT
)
GO

--TABLA CATEGORIA X PRODUCTO
CREATE TABLE TBL_CAT_PROD(
    nIdCatProd INT NOT NULL IDENTITY(1,1) PRIMARY KEY ,
    nIdAlmacen INT,
	FOREIGN KEY (nIdAlmacen) REFERENCES TBL_ALMACEN(nIdAlmacen),   
	nIdCategoria INT,
	FOREIGN KEY (nIdCategoria) REFERENCES TBL_CATEGORIA(nIdCategoria),
	nIdProducto INT
	FOREIGN KEY (nIdProducto) REFERENCES TBL_PRODUCTO(nIdProducto),
)
GO

--TABLA LOTE
CREATE TABLE TBL_LOTE(
    nIdLote INT NOT NULL IDENTITY(1,1) PRIMARY KEY ,
    sNombreLote VARCHAR(MAX),
	dFechaFab DATE,
	dFechaVenc DATE
)
GO

--TABLA UNIDAD MEDIDA
CREATE TABLE TBL_UNIDADMEDIDA(
    nIdUnidadMedida INT NOT NULL IDENTITY(1,1) PRIMARY KEY ,
    sNombre VARCHAR(MAX),
)
GO

--TABLA DETALLE PRODUCTO
CREATE TABLE TBL_DET_PRODUCTO(
    nIdDetProd INT NOT NULL IDENTITY(1,1) PRIMARY KEY ,
    nIdProducto INT,
	FOREIGN KEY (nIdProducto) REFERENCES TBL_PRODUCTO(nIdProducto),
	sDescripcion VARCHAR(MAX),
	nIdUnidadMedida INT,
	FOREIGN KEY (nIdUnidadMedida) REFERENCES TBL_UNIDADMEDIDA(nIdUnidadMedida),
	nCantidad INT ,
	nPrecio INT ,
	nIdLote INT,
)
GO
