USE DB_SISGAPO
GO

--TABLA DOCUMENTOS
CREATE TABLE TBL_DOCUMENTO(
    nIdDocumento INT NOT NULL IDENTITY(1,1) PRIMARY KEY ,
    sNombreDoc VARCHAR(100),
)
GO

--TABLA ROLES
CREATE TABLE TBL_ROL(
    nIdRol INT NOT NULL IDENTITY(1,1) PRIMARY KEY ,
    sNombreRol VARCHAR(100)    
)
GO

--TABLA ZONAS
CREATE TABLE TBL_ZONA(
    nIdZona INT NOT NULL IDENTITY(1,1) PRIMARY KEY ,
    sNombre VARCHAR(MAX),
	sRutaImagen VARCHAR(MAX)
)
GO

--TABLA USUARIOS
CREATE TABLE TBL_USUARIO(
    nIdUsuario INT NOT NULL IDENTITY(1,1) PRIMARY KEY ,
    sNombres VARCHAR(MAX),
	sApellidos VARCHAR(MAX),
	nTipoDoc INT,
    FOREIGN KEY (nTipoDoc) REFERENCES TBL_DOCUMENTO(nIdDocumento),
    sNumDoc VARCHAR(15),
	sSexo VARCHAR(1),
	nRol INT,
    FOREIGN KEY (nRol) REFERENCES TBL_ROL(nIdRol),   
	sDireccion VARCHAR(MAX),
	nTelefono INT,
	dFechaNacimiento DATE,
	bEstado BIT NOT NULL DEFAULT 1
)
GO

--TABLA LOGIN
CREATE TABLE TBL_LOGIN(
    nIdUsuario INT NOT NULL,
	FOREIGN KEY (nIdUsuario) REFERENCES TBL_USUARIO(nIdUsuario),
    sNombreUsuario VARCHAR(100),
    sContrasenia VARCHAR(MAX)
)
GO

--TABLA ALMACEN
CREATE TABLE TBL_ALMACEN(
    nIdAlmacen INT NOT NULL IDENTITY(1,1) PRIMARY KEY ,
    sNombre VARCHAR(MAX),
	sDireccion VARCHAR(MAX),
	nIdSupervisor INT NOT NULL,
	FOREIGN KEY (nIdSupervisor) REFERENCES TBL_USUARIO(nIdUsuario),
	nIdZona INT NOT NULL,
	FOREIGN KEY (nIdZona) REFERENCES TBL_ZONA(nIdZona),
    bEstado BIT NOT NULL DEFAULT 1
)
GO